server:
  port: 8888
  servlet.context-path: /gamble

spring:
  datasource:
    url: 
    username: 
    password: 
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 20
    minIdle: 20
    maxActive: 200
    maxWait: 60000
  mvc:
    static-path-pattern:  /static/**
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5



task:
  flag: false

mybatis:
  typeAliasesPackage: com.ranying.entity
  mapperLocations: classpath:mapper/*.xml

pagehelper:
    helperDialect: mysql                           #分页插件方言选择
    reasonable: true                               #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
    supportMethodsArguments: true

logging:
  config: classpath:logback-spring.xml
  level:
    com.ranying.dao: info
    com.seamax.bdsearch.dao: info

